---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: openmrs-hpa
  labels:
    type: deployment 
    application: openmrs-application
spec:
  maxReplicas: 15
  minReplicas: 3
  targetCPUUtilizationPercentage: 70
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: openmrs-deploy 
