---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: openmrs-deploy
  labels:
    app: openmrs 
    tech: java-11
spec:
  minReadySeconds: 5
  replicas: 4
  selector:
    matchLabels:
      app: openmrs-app
      ver: 1.0
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
  template: 
    metadata:
      name: openmrs-pod
      labels:
        app: openmrs-app
        ver: 1.0
        tech: java-11
    spec:
      containers:
        - image: 
          name: openmrs-container
          ports:
            - containerPort: 8080
              name: openmrs-port
              protocol: TCP
          resources:
            requests:
              memory: "250Mi"
              cpu: "500m"
            limits:
              memory: "750Mi"
              cpu: "1000m"  
          livenessProbe:
            httpGet:
              path: /
              port: 80
          readinessProbe:
            exec:
              command:
                - pwd
                - ls
          volumeMounts:
            - mountPath: /tmp
              name: openmrs-volume
      volumes: 
        - name: openmrs-volume
          persistentVolumeClaim:
            claimName: openmrs-pvc
            
        
