---
apiVersion: v1 
kind: Service
metadata:
  name: openmrs-svc
  labels: 
    app: openmrs
spec:
  selector:
    app: openmrs-app
    ver: 1.0
  type: LoadBlancer 
  ports:
    - port: 8080
      targetPort: 8080
      name: openmrs-app-port
      protocol: TCP  
